#!/usr/bin/env bash
# Copyright 2026 Devin Block
# SPDX-License-Identifier: Apache-2.0

# Spark Video Processor — NMOS (IS-04/IS-05) toolchain bring-up (P0).
#
# Builds Sony's nmos-cpp against Ubuntu 24.04 SYSTEM packages (NO conan), so the control daemon can
# become a full NMOS Node (discover ST 2110-20 video + ST 2110-30 audio senders, IS-05 connection
# management). Mirrors deploy/provision.sh conventions (idempotent, --check, ok/warn/fail).
#
# Why no conan: every nmos-cpp dependency is an apt package on 24.04, and the conan recipes fight the
# host's cmake 4.x. Two gaps the apt packages leave, both handled here:
#   * libcpprest-dev ships no cpprestsdk CMake config -> we generate a shim config (find_library based)
#   * find_package(websocketpp) has no config either  -> use nmos-cpp's WEBSOCKETPP_INCLUDE_DIR bypass
# json-schema-validator + jwt-cpp come from nmos-cpp's own bundled third_party/.
#
# Usage:
#   sudo bash deploy/nmos.sh --packages   # apt-install the dev libraries (needs root; use `!` for pw)
#   bash deploy/nmos.sh --build           # fetch + shim + cmake build (run as your normal user)
#   bash deploy/nmos.sh --check           # report state only, change nothing
#   bash deploy/nmos.sh                    # --packages (if root) then --build
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NMOS_URL="https://github.com/sony/nmos-cpp.git"
NMOS_SRC="$ROOT/third_party/nmos-cpp"
NMOS_BUILD="$NMOS_SRC/build"
SHIM_DIR="$ROOT/third_party/cmake-shims"
PKGS=(cmake g++ git libboost-all-dev libcpprest-dev libwebsocketpp-dev libssl-dev zlib1g-dev \
      nlohmann-json3-dev libavahi-compat-libdnssd-dev libavahi-client-dev)

hr()   { printf '\n===== %s =====\n' "$1"; }
ok()   { printf '  [ok]   %s\n' "$1"; }
info() { printf '  [info] %s\n' "$1"; }
warn() { printf '  [warn] %s\n' "$1"; }
fail() { printf '  [FAIL] %s\n' "$1"; }

MODE="${1:-all}"

# --- packages (root) ------------------------------------------------------------------------------
do_packages() {
  hr "packages (nmos-cpp build deps)"
  if [ "$(id -u)" != 0 ]; then
    fail "must be root: sudo bash deploy/nmos.sh --packages"
    return 1
  fi
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq || warn "apt-get update failed (continuing)"
  if apt-get install -y "${PKGS[@]}"; then ok "packages installed"; else fail "apt-get install failed"; fi
}

check_packages() {
  hr "packages"
  for p in "${PKGS[@]}"; do
    dpkg -s "$p" >/dev/null 2>&1 && ok "$p" || warn "$p MISSING (run: sudo bash deploy/nmos.sh --packages)"
  done
}

# --- fetch source (user) --------------------------------------------------------------------------
do_fetch() {
  hr "fetch nmos-cpp -> third_party/nmos-cpp"
  if [ -d "$NMOS_SRC/.git" ]; then
    ok "already present ($(git -C "$NMOS_SRC" rev-parse --short HEAD 2>/dev/null))"
  else
    mkdir -p "$(dirname "$NMOS_SRC")"
    git clone --depth 1 "$NMOS_URL" "$NMOS_SRC" && ok "cloned" || { fail "git clone failed"; return 1; }
  fi
}

# --- cpprestsdk shim config (user) ----------------------------------------------------------------
# Ubuntu's libcpprest-dev installs the lib + headers but no CMake package config. Recreate the
# cpprestsdk::cpprest imported target that nmos-cpp's find_package(cpprestsdk) expects, resolving the
# real .so/header at configure time so the multiarch path isn't hard-coded.
do_shim() {
  hr "cpprestsdk CMake shim -> third_party/cmake-shims"
  mkdir -p "$SHIM_DIR/cpprestsdk"
  cat > "$SHIM_DIR/cpprestsdk/cpprestsdk-config.cmake" <<'EOF'
# Generated by deploy/nmos.sh — shim for the Ubuntu libcpprest-dev package (no upstream CMake config).
if(NOT TARGET cpprestsdk::cpprest)
  find_library(CPPREST_LIBRARY NAMES cpprest REQUIRED)
  find_path(CPPREST_INCLUDE_DIR NAMES cpprest/http_client.h REQUIRED)
  find_package(Boost REQUIRED COMPONENTS system thread chrono atomic regex filesystem)
  find_package(OpenSSL REQUIRED)
  find_package(ZLIB REQUIRED)
  find_package(Threads REQUIRED)
  add_library(cpprestsdk::cpprest UNKNOWN IMPORTED)
  set_target_properties(cpprestsdk::cpprest PROPERTIES
    IMPORTED_LOCATION "${CPPREST_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${CPPREST_INCLUDE_DIR}"
    INTERFACE_COMPILE_DEFINITIONS "CPPREST_FORCE_PPLX=0"
    INTERFACE_LINK_LIBRARIES "Boost::system;Boost::thread;Boost::chrono;Boost::atomic;Boost::regex;Boost::filesystem;OpenSSL::SSL;OpenSSL::Crypto;ZLIB::ZLIB;Threads::Threads")
endif()
set(cpprestsdk_VERSION "2.10.19")
set(cpprestsdk_FOUND TRUE)
EOF
  cat > "$SHIM_DIR/cpprestsdk/cpprestsdk-config-version.cmake" <<'EOF'
set(PACKAGE_VERSION "2.10.19")
if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
  if(PACKAGE_VERSION VERSION_EQUAL PACKAGE_FIND_VERSION)
    set(PACKAGE_VERSION_EXACT TRUE)
  endif()
endif()
EOF
  ok "wrote cpprestsdk-config.cmake (+ version)"
}

# --- build (user) ---------------------------------------------------------------------------------
do_build() {
  hr "configure + build nmos-cpp (system deps, no conan)"
  [ -d "$NMOS_SRC/Development" ] || { fail "source missing — run --build (does fetch) or check clone"; return 1; }
  # Prefer the apt cmake 3.28 over a /usr/local cmake 4.x: nmos-cpp + its bundled third_party predate
  # cmake 4's removal of <3.5 policy compatibility, so 3.28 configures cleanly without workarounds.
  local CMAKE_BIN; CMAKE_BIN="$( [ -x /usr/bin/cmake ] && echo /usr/bin/cmake || command -v cmake )"
  info "using $($CMAKE_BIN --version | head -1)"
  "$CMAKE_BIN" -S "$NMOS_SRC/Development" -B "$NMOS_BUILD" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
    -Dcpprestsdk_DIR="$SHIM_DIR/cpprestsdk" \
    -DWEBSOCKETPP_INCLUDE_DIR=/usr/include \
    -DNMOS_CPP_USE_SUPPLIED_JSON_SCHEMA_VALIDATOR=ON \
    -DNMOS_CPP_USE_SUPPLIED_JWT_CPP=ON \
    || { fail "cmake configure failed"; return 1; }
  "$CMAKE_BIN" --build "$NMOS_BUILD" -j"$(nproc)" || { fail "build failed"; return 1; }
  ok "built — node: $(ls "$NMOS_BUILD"/nmos-cpp-node 2>/dev/null || echo '?')"
  # install to a prefix so our control daemon can consume it via find_package(nmos-cpp)
  "$CMAKE_BIN" --install "$NMOS_BUILD" --prefix "$NMOS_SRC/install" >/dev/null 2>&1 \
    && ok "installed -> third_party/nmos-cpp/install (find_package(nmos-cpp) ready)" || warn "install step failed"
  # nmos-cpp's install omits the supplied header-only deps that its exported target's include path
  # (include/third_party) points at; copy them so find_package(nmos-cpp) consumers resolve + configure.
  mkdir -p "$NMOS_SRC/install/include/third_party"
  cp -r "$NMOS_SRC/Development/third_party/nlohmann" "$NMOS_SRC/Development/third_party/jwt-cpp" \
        "$NMOS_SRC/install/include/third_party/" 2>/dev/null \
    && ok "staged supplied headers (nlohmann, jwt-cpp) into install/include/third_party"
}

check_build() {
  hr "build"
  [ -d "$NMOS_SRC/.git" ] && ok "source present" || warn "source not fetched"
  [ -f "$SHIM_DIR/cpprestsdk/cpprestsdk-config.cmake" ] && ok "cpprestsdk shim present" || warn "shim not written"
  if [ -x "$NMOS_BUILD/nmos-cpp-node" ]; then ok "nmos-cpp-node built ($NMOS_BUILD/nmos-cpp-node)"
  else warn "nmos-cpp-node not built (run: bash deploy/nmos.sh --build)"; fi
}

# --- run ------------------------------------------------------------------------------------------
case "$MODE" in
  --check)    check_packages; check_build ;;
  --packages) do_packages ;;
  --build)    do_fetch && do_shim && do_build ;;
  all)
    if [ "$(id -u)" = 0 ]; then do_packages; else warn "not root — skipping --packages (run: sudo bash deploy/nmos.sh --packages)"; fi
    do_fetch && do_shim && do_build ;;
  *) fail "unknown mode '$MODE' (use --packages | --build | --check)"; exit 2 ;;
esac

hr "next"
info "registry+node smoke test once built:  $NMOS_BUILD/nmos-cpp-registry  &   $NMOS_BUILD/nmos-cpp-node"
