// Copyright 2026 Devin Block
// SPDX-License-Identifier: Apache-2.0

// Embedded pre-trained super-resolution weight blobs (SRW1 format, see sr_model.hpp).
// The table lives in sr_weights_data.cpp, GENERATED by tools/sr_weights/convert.py from pinned,
// sha256-verified TF frozen graphs (Apache-2.0 sources) so the engine build needs no network,
// Python, or runtime model files.
#pragma once

#include <cstddef>

namespace spark::sr {

struct EmbeddedModel {
  const char* name;  // selection key: "fsrcnn" | "fsrcnn-s" | "espcn"
  const unsigned char* data;
  size_t size;
};

const EmbeddedModel* embedded_models(size_t* count);

}  // namespace spark::sr
